### ISSUE TITLE
Sve dokumente sa rezultatima pismenog ispita postaviti u direktorijum \pismeni-ispiti\info

### ISSUE THREAD

**Issue by vladofilipovic** [MatfUVIT/UVIT#1]

**Comment by ajzenhamernikola** [comment]
@vladofilipovic Da li se ovaj issue odnosi na prethodne ispitne rokove ili na naredne? Ja koliko vidim, rezultati iz JAN1 i JAN2 se vec nalaze u direktorijumu "\pismeni-ispiti\info"

**Comment by vladofilipovic** [comment]
Na naredne rokove. Na slican nacin bi trebalo popunjavati rezulatima i kolokvijume, ako to vec nije uradjeno
