### ISSUE TITLE
Raspodela poena - vežbe 2019/20

### ISSUE THREAD

**Issue by ajzenhamernikola** [MatfUVIT/UVIT#2]
Ukupan broj poena koje nose praktične provere znanja je 65. Predlog je da se za 2019/2020. godinu ti poeni rasporede na sledeći način:
- Prvi praktični kolokvijum
   - 15 poena
   - HTML, CSS
- Drugi praktični kolokvijum
   - 15 poena
   - JavaScript jezik, JavaScript za rad sa DOM stablom
- Praktični deo završnog ispita
   - 35 poena
   - Akcenat na Node.js, MongoDB (uz preostale delove gradiva po potrebi)

**Comment by vladofilipovic** [comment]
Predlog je prihvacen.

Sve najbolje,

  Vlado

--------------------------------------------------
prof. Vladimir Filipović, PhD
Faculty of Mathematics
University of Belgrade
url: http://www.math.rs/~vladaf
email: vladaf@math.rs<mailto:vladaf@math.rs>
            vladofilipovic@hotmail.com<mailto:vladofilipovic@hotmail.com>
cell: +381 64 865 01 19

**Comment by ajzenhamernikola** [comment]
Pragovi prolaznosti:
- Praktični kolokvijumi
   - Nemaju prag
- Praktični deo završnog ispita
  - 15 poena

**Comment by vladofilipovic** [comment]
Azurirao sam github strane kursa tako da odslikavaju postignuti dogovor
