### ISSUE TITLE
Odabir nove teme za sajt kursa

### ISSUE THREAD

**Issue by ajzenhamernikola** [MatfUVIT/UVIT#3]
Da li je "Hacker" tema za sajt kursa odabrana iz nekog posebnog razloga? Ja sam stekao utisak da je teško čitati tekst sa sajta zbog fontova koji su odabrani, kao i zbog prevelikih kontrasta u bojama. Predlažem da porazmislimo o nekoj malo svedenoj temi, kako bi bilo manje naporno učiti iz materijala.

**Comment by vladofilipovic** [comment]
Saglasan.

Dajte predloge. 

Samo, ne bi trebalo da bude ista tema kao ona koju koristim u Banja Luci tj. treba da se razlikuje od https://pmfblos.github.io/OS/

**Comment by ajzenhamernikola** [comment]
Ja predlazem "Slate" ili "Dinky". One mi deluju dosta cisto.

**Comment by vladofilipovic** [comment]
Obe su bas dobre. Vi izaberite i toga cemo se drzati

**Comment by djinx** [comment]
Meni se dopadaju "Slate" i "Cayman".

**Comment by ajzenhamernikola** [comment]
Odabrana je "Slate" tema
